-- KP-Trainer: initial schema (questions, results, feedback)
-- Datenmodell laut KP_Trainer_App_Spezifikation.md

create table if not exists questions (
  id bigint generated by default as identity primary key,
  modul text not null,
  kurs text not null,
  teil smallint not null check (teil in (1, 2, 3)),
  frage text not null,
  bild_frage_url text,
  musterantwort text not null,
  bild_antwort_url text,
  quelle text,
  erstellt_am timestamptz not null default now()
);

create index if not exists questions_modul_idx on questions (modul);
create index if not exists questions_kurs_idx on questions (kurs);
create index if not exists questions_teil_idx on questions (teil);

do $$ begin
  create type bewertung_enum as enum ('richtig', 'teilweise', 'falsch');
exception
  when duplicate_object then null;
end $$;

create table if not exists results (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  question_id bigint not null references questions (id) on delete cascade,
  bewertung bewertung_enum not null,
  nutzer_antwort text not null,
  feedback_text text,
  session_id uuid not null,
  erstellt_am timestamptz not null default now()
);

create index if not exists results_user_id_idx on results (user_id);
create index if not exists results_question_id_idx on results (question_id);
create index if not exists results_session_id_idx on results (session_id);

do $$ begin
  create type feedback_typ_enum as enum ('frage_fehlerhaft', 'antwort_fehlerhaft', 'bild_fehlt_oder_falsch', 'sonstiges');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type feedback_status_enum as enum ('offen', 'erledigt');
exception
  when duplicate_object then null;
end $$;

create table if not exists feedback (
  id bigint generated always as identity primary key,
  question_id bigint not null references questions (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  typ feedback_typ_enum not null,
  kommentar text,
  status feedback_status_enum not null default 'offen',
  erstellt_am timestamptz not null default now()
);

create index if not exists feedback_question_id_idx on feedback (question_id);
create index if not exists feedback_status_idx on feedback (status);

-- Row Level Security
-- questions: lesbar für alle (auch anonyme Nutzer), Schreibzugriff nur über
-- den Service-Role-Key im Admin-Bereich (der RLS umgeht).
alter table questions enable row level security;

create policy "questions_select_all" on questions
  for select using (true);

-- results: Nutzer sehen/schreiben nur ihre eigenen Ergebnisse.
alter table results enable row level security;

create policy "results_select_own" on results
  for select using (auth.uid() = user_id);

create policy "results_insert_own" on results
  for insert with check (auth.uid() = user_id);

-- feedback: Nutzer können eigenes Feedback anlegen und einsehen.
-- Admin-Übersicht läuft über den Service-Role-Key (umgeht RLS).
alter table feedback enable row level security;

create policy "feedback_select_own" on feedback
  for select using (auth.uid() = user_id);

create policy "feedback_insert_own" on feedback
  for insert with check (auth.uid() = user_id);
