-- Phase B (Erweiterung v2): B2 Community-Wartezeit-Tracker
create table if not exists wartezeit_meldungen (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users (id) on delete cascade,
  antrag_datum date not null,
  rechnung_erhalten boolean not null default false,
  rechnung_datum date,
  termin_erhalten boolean not null default false,
  pruefungsdatum date,
  erstellt_am timestamptz not null default now()
);

alter table wartezeit_meldungen enable row level security;

create policy "wartezeit_select_own" on wartezeit_meldungen
  for select using (auth.uid() = user_id);

create policy "wartezeit_insert_own" on wartezeit_meldungen
  for insert with check (auth.uid() = user_id);

create policy "wartezeit_update_own" on wartezeit_meldungen
  for update using (auth.uid() = user_id);

-- Aggregierte Durchschnittswerte serverseitig in SQL berechnen (statt alle
-- Zeilen zu laden und im JS zu mitteln). Views laufen in Postgres standardmäßig
-- mit den Rechten des Eigentümers, umgehen also RLS für diese Aggregation --
-- gewollt, da die Zahlen anonymisiert (nur Durchschnitt + Anzahl) sind.
create or replace view wartezeit_durchschnitt as
select
  avg(rechnung_datum - antrag_datum)
    filter (where rechnung_erhalten and rechnung_datum is not null) as antrag_bis_rechnung_tage,
  count(*)
    filter (where rechnung_erhalten and rechnung_datum is not null) as antrag_bis_rechnung_anzahl,
  avg(pruefungsdatum - rechnung_datum)
    filter (where termin_erhalten and pruefungsdatum is not null and rechnung_datum is not null)
    as rechnung_bis_termin_tage,
  count(*)
    filter (where termin_erhalten and pruefungsdatum is not null and rechnung_datum is not null)
    as rechnung_bis_termin_anzahl,
  count(*) as gesamt_meldungen
from wartezeit_meldungen;

grant select on wartezeit_durchschnitt to authenticated;
