-- Phase C (Erweiterung v2): Marketplace (Angebote, Nachrichten, Kommentare)

do $$ begin
  create type angebot_kategorie as enum ('simulation_kostenlos', 'kurs_kostenpflichtig', 'buch', 'sonstiges');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type angebot_status as enum ('aktiv', 'inaktiv');
exception
  when duplicate_object then null;
end $$;

create table if not exists angebote (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  kategorie angebot_kategorie not null,
  titel text not null,
  beschreibung text not null,
  preis text,
  status angebot_status not null default 'aktiv',
  erstellt_am timestamptz not null default now()
);

create index if not exists angebote_kategorie_idx on angebote (kategorie);
create index if not exists angebote_status_idx on angebote (status);

alter table angebote enable row level security;

create policy "angebote_select_all" on angebote for select using (true);
create policy "angebote_insert_own" on angebote for insert with check (auth.uid() = user_id);
create policy "angebote_update_own" on angebote for update using (auth.uid() = user_id);
create policy "angebote_delete_own" on angebote for delete using (auth.uid() = user_id);

create table if not exists angebot_nachrichten (
  id bigint generated by default as identity primary key,
  angebot_id bigint not null references angebote (id) on delete cascade,
  user_id_von uuid not null references auth.users (id) on delete cascade,
  user_id_an uuid not null references auth.users (id) on delete cascade,
  text text not null,
  gelesen boolean not null default false,
  erstellt_am timestamptz not null default now()
);

create index if not exists angebot_nachrichten_angebot_idx on angebot_nachrichten (angebot_id);
create index if not exists angebot_nachrichten_an_idx on angebot_nachrichten (user_id_an);

alter table angebot_nachrichten enable row level security;

create policy "nachrichten_select_beteiligt" on angebot_nachrichten
  for select using (auth.uid() = user_id_von or auth.uid() = user_id_an);

create policy "nachrichten_insert_als_von" on angebot_nachrichten
  for insert with check (auth.uid() = user_id_von);

create policy "nachrichten_update_als_empfaenger" on angebot_nachrichten
  for update using (auth.uid() = user_id_an);

create table if not exists angebot_kommentare (
  id bigint generated by default as identity primary key,
  angebot_id bigint not null references angebote (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  text text not null,
  erstellt_am timestamptz not null default now()
);

create index if not exists angebot_kommentare_angebot_idx on angebot_kommentare (angebot_id);

alter table angebot_kommentare enable row level security;

create policy "kommentare_select_all" on angebot_kommentare for select using (true);
create policy "kommentare_insert_own" on angebot_kommentare for insert with check (auth.uid() = user_id);
create policy "kommentare_delete_own" on angebot_kommentare for delete using (auth.uid() = user_id);
