-- Melde-System: Angebote/Nachrichten/Kommentare können gemeldet werden und
-- werden dann sofort für alle Nutzer (außer Admin, der über den Service-Role-
-- Key läuft und RLS umgeht) verborgen, bis ein Admin die Meldung geprüft hat.

alter table angebote add column if not exists versteckt boolean not null default false;
alter table angebot_nachrichten add column if not exists versteckt boolean not null default false;
alter table angebot_kommentare add column if not exists versteckt boolean not null default false;

-- Select-Policies neu fassen, damit verborgene Inhalte für niemanden (außer
-- Admin über Service-Role) sichtbar sind.
drop policy if exists "angebote_select_all" on angebote;
create policy "angebote_select_sichtbar" on angebote for select using (not versteckt);

drop policy if exists "nachrichten_select_beteiligt" on angebot_nachrichten;
create policy "nachrichten_select_beteiligt" on angebot_nachrichten
  for select using ((auth.uid() = user_id_von or auth.uid() = user_id_an) and not versteckt);

drop policy if exists "kommentare_select_all" on angebot_kommentare;
create policy "kommentare_select_sichtbar" on angebot_kommentare for select using (not versteckt);

do $$ begin
  create type melde_typ as enum ('angebot', 'nachricht', 'kommentar');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type melde_grund as enum ('spam', 'betrug', 'unangemessen', 'sonstiges');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type melde_status as enum ('offen', 'erledigt');
exception
  when duplicate_object then null;
end $$;

create table if not exists meldungen (
  id bigint generated by default as identity primary key,
  inhalt_typ melde_typ not null,
  inhalt_id bigint not null,
  gemeldet_von uuid not null references auth.users (id) on delete cascade,
  grund melde_grund not null,
  kommentar text,
  status melde_status not null default 'offen',
  erstellt_am timestamptz not null default now()
);

create index if not exists meldungen_status_idx on meldungen (status);
create index if not exists meldungen_inhalt_idx on meldungen (inhalt_typ, inhalt_id);

alter table meldungen enable row level security;

-- Nur Insert für eigene Meldungen; lesen/verwalten läuft ausschließlich über
-- den Admin-Bereich mit Service-Role-Key.
create policy "meldungen_insert_own" on meldungen
  for insert with check (auth.uid() = gemeldet_von);
