-- Phase D (Erweiterung v2): D1 Öffentliche Kommentare zu Musterantworten.
-- Nutzt das bestehende generische Melde-System (melde_typ/meldungen) mit.

alter type melde_typ add value if not exists 'antwort_kommentar';

create table if not exists antwort_kommentare (
  id bigint generated by default as identity primary key,
  question_id bigint not null references questions (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  text text not null,
  versteckt boolean not null default false,
  erstellt_am timestamptz not null default now()
);

create index if not exists antwort_kommentare_question_idx on antwort_kommentare (question_id);

alter table antwort_kommentare enable row level security;

create policy "antwort_kommentare_select_sichtbar" on antwort_kommentare
  for select using (not versteckt);

create policy "antwort_kommentare_insert_own" on antwort_kommentare
  for insert with check (auth.uid() = user_id);
