-- Phase D (Erweiterung v2): D2 Nutzer-Einreichungen (Einzelfrage/Protokoll)
-- mit Admin-Freigabe.

do $$ begin
  create type einreichung_typ as enum ('einzelfrage', 'protokoll');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type einreichung_status as enum ('offen', 'freigegeben', 'abgelehnt');
exception
  when duplicate_object then null;
end $$;

create table if not exists einreichungen (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  typ einreichung_typ not null,
  modul text,
  kurs text,
  teil smallint,
  frage text,
  antwort_vorschlag text,
  protokoll_text text,
  status einreichung_status not null default 'offen',
  admin_kommentar text,
  erstellt_am timestamptz not null default now()
);

create index if not exists einreichungen_status_idx on einreichungen (status);
create index if not exists einreichungen_user_idx on einreichungen (user_id);

alter table einreichungen enable row level security;

create policy "einreichungen_select_own" on einreichungen
  for select using (auth.uid() = user_id);

create policy "einreichungen_insert_own" on einreichungen
  for insert with check (auth.uid() = user_id);
